services:
  - type: web
    name: tia-db-converter
    env: python
    plan: starter
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn --workers=1 --bind 0.0.0.0:10000 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
